---
- name: Baseline Windows
  hosts: windows
  tasks:
    - name: Install packages
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item }}"
        state: latest
      loop:
        - nodejs-lts
        - powershell-core
        - vscode
