variables:
  - template: ./.azure-pipelines/variables.yml

name: ${{variables.name}}-pipeline

trigger:
  - main

stages:
- stage: test
  displayName: CloudFormation Tests
  pool:
    vmImage: ${{ variables.vmImage }}
  jobs:
    - job: cfnTests
      displayName: CFN Templates Tests
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: ${{ variables.pythonVersion }}
        displayName: Use Python ${{ variables.pythonVersion }}
      - script: python -m pip install --upgrade pip
        displayName: 'Install Python Tools'
      - script: pip install cfn-lint==${{ variables.cfnlintVersion }}
        displayName: 'Install cfn-lint'
      - script: cfn-lint --include-checks I -t cloudformation/**/*.yml
        displayName: 'Run cfn-lint'
    - job: jsonTests
      displayName: CFN Parameters Tests
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: ${{ variables.nodejsVersion }}
        displayName: Use Node.js ${{ variables.nodejsVersion }}
      - task: Npm@1
        inputs:
          command: custom
          customCommand: set-script prepare ""
        displayName: 'Disable npm Install Hook'
      - task: Npm@1
        inputs:
          command: ci
        displayName: 'Install npm Packages'
      - bash: find cloudformation -type f -name "*.json" -exec npx jsonlint -cq {} \;
        displayName: 'Run json-lint'
