---
- name: Deploy Azure ARM Template
  hosts: localhost
  vars_prompt:
    - name: vm_resource_group
      prompt: The resource group for the VM resources
      private: no
    - name: location
      prompt: The location for the resources
      private: no
    - name: admin_username
      prompt: The admin username for the Virtual Machine
      private: no
    - name: admin_password
      prompt: The admin password for the Virtual Machine
      private: yes
    - name: vm_size
      prompt: Size of the virtual machine
      private: no
    - name: vm_name
      prompt: Name of the virtual machine
      private: no
    - name: vnet_id
      prompt: ID of the virtual network
      private: no
    - name: storage_account_name
      prompt: Name of the storage account for diagnostics
      private: no
    - name: os_disk_type
      prompt: OS Disk storage type
      private: no
    - name: os_version
      prompt: The Windows version for the VM
      private: no
    - name: vnet_id
      prompt: ID of the virtual network
      private: no
    - name: subnet_name
      prompt: Name of the subnet
      private: no
    - name: enable_acc_net
      prompt: Enable accelerated networking?
      private: no
    - name: public_ip_address_type
      prompt: Public IP address type
      private: no
    - name: public_ip_address_sku
      prompt: Public IP address type SKU
      private: no

  vars:
    pip_delete_option: Delete
    os_disk_delete_option: Delete
    nic_delete_option: Delete
    patch_mode: AutomaticByOS
    enable_hot_patching: false
    network_interface_name: "{{ vm_name }}-nic0"
    public_ip_address_name: "{{ vm_name }}-pip0"
    group_tags:
      - key: "source"
        value: ansible

  tasks:
    - name: Deploy resources to {{ vm_resource_group }}
      azure.azcollection.azure_rm_deployment:
        deployment_mode: incremental # Set to 'complete' to delete other resources in the resource group
        deployment_name: "{{ vm_name }}-{{ ansible_date_time.iso8601_basic_short }}"
        location: "{{ location }}"
        resource_group: "{{ vm_resource_group }}"
        parameters:
          location:
            value: "{{ location }}"
          networkInterfaceName:
            value: "{{ network_interface_name }}"
          enableAcceleratedNetworking:
            value: "{{ enable_acc_net }}"
          subnetName:
            value: "{{ subnet_name }}"
          virtualNetworkId:
            value: "{{ vnet_id }}"
          publicIpAddressName:
            value: "{{ public_ip_address_name }}"
          publicIpAddressType:
            value: "{{ public_ip_address_type }}"
          publicIpAddressSku:
            value: "{{ public_ip_address_sku }}"
          pipDeleteOption:
            value: "{{ pip_delete_option }}"
          virtualMachineName:
            value: "{{ vm_name }}"
          virtualMachineComputerName:
            value: "{{ vm_name }}"
          virtualMachineRG:
            value: "{{ vm_resource_group }}"
          osVersion:
            value: "{{ os_version }}"
          osDiskType:
            value: "{{ os_disk_type }}"
          osDiskDeleteOption:
            value: "{{ os_disk_delete_option }}"
          virtualMachineSize:
            value: "{{ vm_size }}"
          nicDeleteOption:
            value: "{{ nic_delete_option }}"
          adminUsername:
            value: "{{ admin_username }}"
          adminPassword:
            value: "{{ admin_password }}"
          patchMode:
            value: "{{ patch_mode }}"
          enableHotpatching:
            value: "{{ enable_hot_patching }}"
          diagnosticsStorageAccountName:
            value: "{{ storage_account_name }}"
        template: "{{ lookup('file', '../../arm/virtual-machines/windows-vm-standalone.json') }}"
        tags: "{{ group_tags | items2dict }}"
