---
- name: Deploy Azure Virtual Network
  hosts: localhost
  vars_prompt:
    - name: resource_group_name
      prompt: The resource group for the resources
      private: no
    - name: vnet_name
      prompt: The name of the virtual network
      private: no
    - name: vnet_address_prefix
      prompt: The prefix of the virtual network
      private: no
    - name: subnet_1_prefix
      prompt: The prefix of the first subnet
      private: no
    - name: subnet_1_name
      prompt: The name of the first subnet
      private: no
    - name: subnet_2_prefix
      prompt: The prefix of the second subnet
      private: no
    - name: subnet_2_name
      prompt: The name of the second subnet
      private: no

  vars:
    group_tags:
      - key: "source"
        value: ansible

  tasks:
    - name: Deploy virtual network to {{ resource_group_name }}
      azure.azcollection.azure_rm_deployment:
        deployment_mode: incremental # Set to 'complete' to delete other resources in the resource group
        deployment_name: "{{ vnet_name }}-{{ ansible_date_time.iso8601_basic_short }}"
        location: "{{ location }}"
        resource_group: "{{ resource_group_name }}"
        parameters:
          vnetName:
            value: "{{ vnet_name }}"
          vnetAddressPrefix:
            value: "{{ vnet_address_prefix }}"
          subnet1Prefix:
            value: "{{ subnet_1_prefix }}"
          subnet1Name:
            value: "{{ subnet_1_name }}"
          subnet2Prefix:
            value: "{{ subnet_2_prefix }}"
          subnet2Name:
            value: "{{ subnet_2_name }}"
          location:
            value: "{{ location }}"
        template: "{{ lookup('file', '../../arm/networking/virtual-network.json') }}"
        tags: "{{ group_tags | items2dict }}"
