---
- name: Deploy CloudFormation
  hosts: localhost
  vars_prompt:
    - name: keypair
      prompt: Specify the name of the key pair
      private: no
    - name: vpc_id
      prompt: Specify the ID of the host VPC
      private: no
    - name: subnet_id
      prompt: Specify the ID of the host subnet
      private: no
    - name: stackname
      prompt: Specify the name for the stack
      private: no

  tasks:
    - name: Deploy CloudFormation stack {{ stackname }}
      amazon.aws.cloudformation:
        stack_name: "{{ stackname }}"
        state: "present"
        capabilities: CAPABILITY_NAMED_IAM
        template: "../../cloudformation/ec2/windows-single-instance/ec2-windows-single-instance.yml"
        template_parameters:
          AmiId: ami-0708af7afa9230e4f # Windows Server 2019
          InstanceType: t3a.large
          KeyPairName: "{{ keypair }}"
          OpsLocation0001: 0.0.0.0/0
          RemoteDesktopPort: 3389
          WinRmPort: 5986
          RootDeviceName: sda1
          RootVolumeSize: 48
          RootVolumeType: gp2
          SubnetId: "{{ subnet_id }}"
          VpcId: "{{ vpc_id }}"
