
variables:
  - template: ../.azure-pipelines/variables.yml
  - group: ${{variables.name}}-all
  - group: ${{variables.name}}-dev

name: ${{variables.name}}-pipeline

resources:
  repositories:
    - repository: templates
      type: git
      name: sje-ado-labs/ado-pipeline-templates
      ref: refs/tags/latest

trigger:
  - master

stages:
- template: ../.azure-pipelines/deploy-cfn.yml
  parameters:
    vmImage: ${{ variables.vmImage }}
    nodejsVersion: ${{ variables.nodejsVersion }}
    serviceConnection: ${{ variables.serviceConnection }}
    awsRegion: ${{ variables.awsRegion }}
    # awsS3CfnBucket: ${{ variables.awsS3CfnBucket }}
    environment: lab
    stackName: lab-test-cfn-0001
    templateFile: template-ssm-params.yml
    runtimeSecrets:
      thirdName: $(third)
      fourthName: $(fourth)
