parameters:
  - name: vmImage
    type: string
  - name: nodejsVersion
    type: string
  - name: serviceConnection
    type: string
  - name: awsRegion
    type: string
  # - name: awsS3CfnBucket FIXME
  #   type: string
  - name: environment
    type: string
  - name: templateFile
    type: string
  - name: stackName
    type: string
  - name: runtimeSecrets
    type: object
    default:
      firstName: first
      secondName: second

stages:
  - stage: deployCfn
    displayName: Deploy CFN for ${{ parameters.environment }}
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    variables:
      - name: cfnArtifactName
        value: cfn-${{ parameters.stackName }}-$(System.JobAttempt)
      - name: cfnFileName
        value: ${{ parameters.stackName }}.yml
    jobs:
      - job: buildCfnTemplate
        displayName: Build CFN Template for ${{ parameters.stackName }}
        pool:
          vmImage: ${{ parameters.vmImage }}
        steps:
          - task: NodeTool@0
            displayName: Use Node.js ${{ parameters.nodejsVersion }}
            inputs:
              versionSpec: ${{ parameters.nodejsVersion }}
          - bash: |
              echo '${{ convertToJson(parameters.runtimeSecrets) }}' | node ./index.js /dev/stdin ${{ parameters.templateFile }} > $(Agent.TempDirectory)/$(cfnFileName)
            workingDirectory: $(Agent.BuildDirectory)/s/bandolier
            name: compileCfnTemplate
            displayName: Compile CFN Template for ${{ parameters.stackName }}
          - publish: $(Agent.TempDirectory)/$(cfnFileName)
            artifact: $(cfnArtifactName)
            name: publishCfnTemplate
            displayName: Publish CFN Template for ${{ parameters.stackName }}
      - deployment: runCfn
        displayName: Run CFN for ${{ parameters.environment }}
        dependsOn: buildCfnTemplate
        pool:
          vmImage: ${{ parameters.vmImage }}
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
              - task: CloudFormationCreateOrUpdateStack@1
                displayName: "Deploy CFN Stack ${{ parameters.stackName }}"
                inputs:
                  awsCredentials: ${{ parameters.serviceConnection }}
                  regionName: ${{ parameters.awsRegion }}
                  stackName: ${{ parameters.stackName }}
                  templateSource: file
                  templateFile: $(Pipeline.Workspace)/$(cfnArtifactName)/$(cfnFileName)
                  # s3BucketName: ${{ parameters.awsS3CfnBucket }} FIXME
                  tags: |
                    sje:resource:environment=$(Environment.Name)
                    sje:ci:pipeline=$(Build.DefinitionName)
                    sje:ci:jobid=$(System.JobId)
                    sje:vcs:repo=$(Build.Repository.Name)
                    sje:vcs:branch=$(Build.SourceBranchName)
                    sje:vcs:commit=$(Build.SourceVersion)
