AWSTemplateFormatVersion: "2010-09-09"
Description: |
  {{description}}

Resources:
{{#each items}}
  Secret{{cap this.key}}:
    Type: AWS::SSM::Parameter
    Properties:
      Name: {{cap this.key}}
      Description: {{cap this.key}}
      Type: String
      Value: {{this.value}}

{{/each}}
