# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Configuration for the just task runner
#
# See https://just.systems

# List available recipes
help:
    @just --list

# Test
test:
    @python3 -m pytest
