# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Python development tasks for the Task runner:
#
# https://taskfile.dev

version: "3"

silent: true

includes:
  venv: ../tasks/uv

tasks:
  default:
    cmds:
      - task: list

  bootstrap:
    desc: Set up environment for development
    aliases: [setup]
    cmds:
      - task: venv:compile
      - task: venv:sync

  fmt:
    desc: Format code
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - python3 -m ruff format

  list:
    desc: List available tasks
    cmds:
      - task --list

  test:
    desc: Run Python tests
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - python3 -m pytest
