# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Tasks for the Task runner:
#
# https://taskfile.dev/

version: "3"

silent: true

tasks:

  test:
    desc: Run Python tests
    cmds:
      - python3 -m pytest
