---
- name: Deploy CloudFormation
  hosts: localhost
  vars_prompt:
    - name: keypair
      prompt: Specify the name of the key pair
      private: no
    - name: stackname
      prompt: Specify the name for the stack
      private: no

  tasks:
    - name: Deploy CloudFormation stack {{ stackname }}
      amazon.aws.cloudformation:
        stack_name: "{{ stackname }}"
        state: "present"
        capabilities: CAPABILITY_NAMED_IAM
        template: "../cloudformation/ec2/linux-single-instance/ec2-linux-single-instance.yml"
        template_parameters:
          AmiId: ami-04b683923501a6f2c # x84-64 Ubuntu 20.04
          InstanceType: t3a.small
          KeyPairName: "{{ keypair }}"
          OpsLocation0001: 0.0.0.0/0
          SshPort: 22
          RootDeviceName: sda1
          RootVolumeSize: 12
          RootVolumeType: gp2
          SubnetId: subnet-252e3d6d
          VpcId: vpc-44be683d
